import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/components/Navbar";
import { LocationProvider } from "@/lib/LocationContext";
import "./globals.css"; // Global CSS
import "aos/dist/aos.css";
import "owl.carousel/dist/assets/owl.carousel.css";
import "owl.carousel/dist/assets/owl.theme.default.css";

import AOSInit from "@/components/AOSInit";
import Footer from "@/components/Footer";

import Script from "next/script";
import { Inter } from "next/font/google";
// Initialize Google Font (optional)
const inter = Inter({ subsets: ["latin"] });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="/assets/css/bootstrap.min.css" />
        <link rel="stylesheet" href="/assets/css/fontawesome-all.css" />
        <link rel="stylesheet" href="/assets/css/owl.carousel.css" />
        <link rel="stylesheet" href="/assets/css/animate.min.css" />
        <link rel="stylesheet" href="/assets/css/lightbox.css" />
        <link rel="stylesheet" href="/assets/css/video.min.css" />
        <link rel="stylesheet" href="/assets/css/flaticon.css" />
        <link rel="stylesheet" href="/assets/css/meanmenu.css" />
        <link rel="stylesheet" href="/assets/css/progess.css" />
        <link rel="stylesheet" href="/assets/css/style.css" />
        <link rel="stylesheet" href="/assets/css/code.css" />
        <link rel="stylesheet" href="/assets/css/custom.css" />
        <link rel="stylesheet" href="/assets/css/responsive.css" />
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.className} antialiased`}
      >
        <LocationProvider>
          <Navbar />
          <main>
            <AOSInit />
            {children}
            <Footer />
          </main>
        </LocationProvider>
        {/* External Scripts */}
        <Script
          src="/assets/js/jquery-2.1.4.min.js"
          strategy="beforeInteractive"
        ></Script>
        <Script
          src="/assets/js/bootstrap.min.js"
          strategy="beforeInteractive"
        ></Script>
        <Script src="/assets/js/popper.min.js"></Script>
        <Script src="/assets/js/jarallax.js"></Script>
        <Script src="/assets/js/jquery.magnific-popup.min.js"></Script>
        <Script src="/assets/js/lightbox.js"></Script>
        <Script src="/assets/js/jquery.meanmenu.js"></Script>
        <Script src="/assets/js/scrollreveal.min.js"></Script>
        <Script src="/assets/js/jquery.counterup.min.js"></Script>
        <Script src="/assets/js/waypoints.min.js"></Script>
        <Script src="/assets/js/jquery-ui.js"></Script>
        <Script src="/assets/js/gmap3.min.js"></Script>
        <Script src="/assets/js/switch.js"></Script>
        <Script src="/assets/js/script.js" defer></Script>
      </body>
    </html>
  );
}
